### PR TITLE
Add NowPlaying status, UserPlayCount and UserLoved

### PR DESCRIPTION
**Pull request by mx2rel**

### CODE REVIEW

**Comment by mx2rel** [comment]
@wo80 review and merge would be greatly appreciated.

**Comment by wo80** [comment]
@mx2rel Please be a bit more communicative. If I'd known a follow up pull requests was to come, I hadn't released a new version on Nuget. So, what are your plans?

And a general tip regarding contributions to open source projects and git: never do your changes on the master/main branch. Always create working branches for new features or fixes. This way the commit history will look much cleaner and you can pull upstream changes anytime, and if necessary update your working branches by rebasing or - less desirable - by merging those changes.

**Comment by mx2rel** [comment]
Hi @wo80 ,

Thank you for the feedback. I apologize for any inconvenience caused.
Currently, I’m developing my own project using this Last.fm API wrapper and addressing fixes and new features as needed. I don't have strict plans laid out, so I can't provide a detailed scope of future changes.

I also appreciate the tip regarding contributions to open source projects and Git workflow. This is my first time seriously contributing to an open source project, and I will try to follow your advice moving forward.

Best regards,
Marcel

**Comment by wo80** [comment]
@mx2rel No need to apologize, your contributions are very welcome! Just wanted to know whether there are any plans for further changes before doing the next Nuget release. I will merge this soon.

**Comment by wo80** [comment]
For explanation: the reason why the master branch of your fork and this repo diverged is because I [squashed](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits) your last pull request. That's another good reason to make changes only on working branches, so the master branch stays in sync with upstream.

**Pull request merged**
